apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ioooikaak/gateway:2.0.0
          imagePullPolicy: Always
          ports:
           - containerPort: 3201
             name: gateway
             protocol: TCP
          #resources:
            #requests:
              #memory: "1Gi"
              #cpu: "1000m"
            #limits:
              #memory: "4Gi"
              #cpu: "2000m"
          #volumeMounts:
            #- mountPath: /var/lib/gateway
              #name: data-gateway
  #updateStrategy:
    #type: OnDelete
  #volumeClaimTemplates:
    #- metadata:
        #name: data-gateway
      #spec:
        #accessModes: [ "ReadWriteMany" ]
        #storageClassName: storageclass-default
        #resources:
          #requests:
            #storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 3201
    targetPort: 3201
    name: gateway
  selector:
    app: gateway
